"""added event title

Revision ID: 181fb8674f04
Revises: b1bcec5e52c2
Create Date: 2024-01-30 07:09:24.393938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181fb8674f04'
down_revision: Union[str, None] = 'b1bcec5e52c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('event_title', sa.String(), nullable=True))
    op.create_index(op.f('ix_calendar_event_title'), 'calendar', ['event_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_event_title'), table_name='calendar')
    op.drop_column('calendar', 'event_title')
    # ### end Alembic commands ###
