"""added company id to calendar mode

Revision ID: 327dc447ebdd
Revises: 0a13452cc2e8
Create Date: 2024-01-28 12:02:18.710984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327dc447ebdd'
down_revision: Union[str, None] = '0a13452cc2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('company_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_calendar_company_id'), 'calendar', ['company_id'], unique=False)
    op.add_column('quote', sa.Column('company_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_quote_company_id'), 'quote', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_company_id'), table_name='quote')
    op.drop_column('quote', 'company_id')
    op.drop_index(op.f('ix_calendar_company_id'), table_name='calendar')
    op.drop_column('calendar', 'company_id')
    # ### end Alembic commands ###
