"""allow dates nullable

Revision ID: 8cecef8eb207
Revises: aba422da83b8
Create Date: 2024-01-30 18:10:44.686412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cecef8eb207'
down_revision: Union[str, None] = 'aba422da83b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'scheduled_start_date_and_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('calendar', 'scheduled_end_date_and_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'scheduled_end_date_and_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('calendar', 'scheduled_start_date_and_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
