"""added new field all day

Revision ID: aba422da83b8
Revises: ff3a88073b1d
Create Date: 2024-01-30 16:13:23.363084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba422da83b8'
down_revision: Union[str, None] = 'ff3a88073b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('all_day', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_calendar_all_day'), 'calendar', ['all_day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_all_day'), table_name='calendar')
    op.drop_column('calendar', 'all_day')
    # ### end Alembic commands ###
