"""allow event type nullable

Revision ID: b32d590cee65
Revises: 8cecef8eb207
Create Date: 2024-01-30 19:51:03.062586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32d590cee65'
down_revision: Union[str, None] = '8cecef8eb207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
