"""amended field to be nullable

Revision ID: ff3a88073b1d
Revises: 181fb8674f04
Create Date: 2024-01-30 10:46:47.554457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3a88073b1d'
down_revision: Union[str, None] = '181fb8674f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'quote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'quote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
